version: 1
builder:
  configs:
    - platform: ios
      documentation_targets:
        - AtatusCore
        - AtatusLogs
        - AtatusTrace
        - AtatusRUM
        - AtatusSessionReplay
        - AtatusCrashReporting
        - AtatusWebViewTracking
        - AtatusFlags
        - AtatusProfiling
