## Workaround KSCrash static linking issue
# https://github.com/kstenerud/KSCrash/issues/713
use_modular_headers!
#

target 'Runner iOS' do
    platform :ios, '12.0'

    pod 'AtatusCore', :path => '..'
    pod 'AtatusLogs', :path => '..'
    pod 'AtatusTrace', :path => '..'
    pod 'AtatusRUM', :path => '..'
    pod 'AtatusCrashReporting', :path => '..'
    pod 'AtatusSessionReplay', :path => '..'
    pod 'AtatusWebViewTracking', :path => '..'

    target 'IntegrationScenarios' do
        pod 'AtatusInternal', :path => '..'
        pod 'TestUtilities', :path => '..'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) DD_SDK_ENABLE_EXPERIMENTAL_APIS DD_SDK_COMPILED_FOR_TESTING'
        end
    end
end
